GoCebuTravelAndToursMVC/Models/ListTourPackageViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GoCebuTravelAndToursMVC.Models
{
    public class ListTourPackageViewModel
    { 

        [Display(Name = "Search Tour Package")]
        public String TourPackageName { get; set; }

        public List<TourPackage> TourPackages { get; set; }
    }
}

GoCebuTravelAndToursMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using GoCebuTravelAndToursMVC.Models;

namespace GoCebuTravelAndToursMVC.Controllers
{

    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            GoCebuDBEntities entities = new GoCebuDBEntities();

            try
            {
                return View(entities.TourPackages.Where(T => T.EnabledFlag == true && T.BestSellerFlag == true 
                && !string.IsNullOrEmpty(T.CaroImgFileName))
                    .OrderBy(T => T.OrderByDisplay).ToList());
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }


            return View();
        }

        [ChildActionOnly]
        public PartialViewResult Reviews()
        {
            GoCebuDBEntities entities = new GoCebuDBEntities();

            try
            {
                return PartialView(entities.Reviews.Where(T => T.EnabledFlag == true).OrderBy(T => T.Id).ToList());
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }


            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult ListTourPackages()
        {

            GoCebuDBEntities entities = new GoCebuDBEntities();

            try
            {
                ListTourPackageViewModel listTourPackageViewModel = new ListTourPackageViewModel
                {
                    TourPackageName = null,
                    TourPackages = entities.TourPackages.Where(T => T.EnabledFlag == true && T.GroupBy == "Day")
                    .OrderBy(T => T.OrderByDisplay).ToList()
                };

                return PartialView(listTourPackageViewModel);
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }


            return PartialView();
        }

    }
}

GoCebuTravelAndToursMVC/Controllers/TourController.cs
using GoCebuTravelAndToursMVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;

namespace GoCebuTravelAndToursMVC.Controllers
{
    public class TourController : Controller
    {
        // GET: Tour
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult ListTourPackages(string groupBy)
        {
            GoCebuDBEntities entities = new GoCebuDBEntities();

            try
            {
                if (groupBy != null)
                {
                    var results = entities.TourPackages
                        .Where(T => T.GroupBy.Contains(groupBy))
                        .Where(T => T.EnabledFlag == true)
                        .OrderBy(T => T.OrderByDisplay)
                        .OrderBy(T => T.Id)
                        .ToList();

                    if (groupBy == "all")
                    {
                        results = entities.TourPackages.Where(T => T.EnabledFlag == true).OrderBy(T => T.OrderByDisplay).ToList();
                    }

                    ViewBag.groupBy = groupBy;

                    if (results.Count == 0)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    return View(results);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }

            return RedirectToAction("Index", "Home");
        }

        // GET: TourPackage Displays Data in Tour/TourPackage
        public ActionResult TourPackage(int? id, string groupBy)
        {

            Session["BOOKING"] = null;

            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            GoCebuDBEntities entities = new GoCebuDBEntities();
            try
            {
                ViewBag.groupBy = groupBy;

                TourPackageViewModel tourPackage = new TourPackageViewModel()
                {
                    TourPackage = entities.TourPackages.Find(id),
                    TourPackagePrices = entities.TourPackagePrices.Where(T => T.TourPackageId == id && T.EnabledFlag == true)   
                                        .OrderBy(T => T.Pax).ToList(),
                    TourGalleries = entities.TourGalleries.Where(T => T.TourPackageId == id).ToList()
                };

                var dateTime = DateTime.Now;

                tourPackage.BookingViewModel = new BookingViewModel()
                {
                    TourPackageId = tourPackage.TourPackage.Id,
                    TourPackageName = tourPackage.TourPackage.TourPackageName,
                    TourDurationInHours = (int)tourPackage.TourPackage.TourDurationInHours
                };

                //get max pax number
                tourPackage.MaxPax = (int)entities.TourPackagePrices
                    .Where(T => T.TourPackageId == tourPackage.BookingViewModel.TourPackageId)
                    .Max(T => T.Pax);


                tourPackage.TourPackageAddOns = entities.TourPackageAddOns.Where(T => T.TourPackageId == id).ToList();


                if (tourPackage.TourPackage == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                return View(tourPackage);
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult TourPackage(TourPackageViewModel tourPackage, int[] tourPackageAddOnsIds)
        {

            if (tourPackage.BookingViewModel == null)
            {
                return RedirectToAction("Index", "Home");
            }

            GoCebuDBEntities entities = new GoCebuDBEntities();

            try
            {
                if (Session["BOOKING"] == null)
                {
                    var tourPackageDetails = entities.TourPackages
                        .Where(T => T.Id == tourPackage.BookingViewModel.TourPackageId)
                        .FirstOrDefault();

                    tourPackage.TourPackage = new TourPackage() { };
                    
                    //get base tourpackage price
                    var tourPackagePrice = entities.TourPackagePrices
                                                    .Where(T => T.TourPackageId == tourPackage.BookingViewModel.TourPackageId
                                                        && T.Pax == (tourPackage.BookingViewModel.TotalLocalGuest + 
                                                                        tourPackage.BookingViewModel.TotalForeignGuest))
                                                    .FirstOrDefault();

                    if (tourPackagePrice != null)
                    {
                        //get pax amount by number of guest
                        tourPackage.BookingViewModel.TourPackagePrice = (decimal)(tourPackagePrice.Amount * tourPackagePrice.Pax);
                    }
                    else
                    {
                        //get max pax number
                        var maxPax = entities.TourPackagePrices
                            .Where(T => T.TourPackageId == tourPackage.BookingViewModel.TourPackageId)
                            .Max(T => T.Pax);

                        //get maximum pax amount
                        tourPackagePrice = entities.TourPackagePrices
                        .Where(T => T.TourPackageId == tourPackage.BookingViewModel.TourPackageId
                        && T.Pax == maxPax).FirstOrDefault();

                    }

                    tourPackage.BookingViewModel.TotalAmountEach = (decimal)tourPackagePrice.Amount;

                    //Local amount base price
                    tourPackage.BookingViewModel.TotalLocalGuestAmount = tourPackage.BookingViewModel.TotalAmountEach * (int)tourPackage.BookingViewModel.TotalLocalGuest;

                    //Foreign amount base price
                    tourPackage.BookingViewModel.TotalForeignAmount = tourPackage.BookingViewModel.TotalAmountEach * (int)tourPackage.BookingViewModel.TotalForeignGuest;

                    tourPackage.BookingViewModel.TotalAmount = tourPackage.BookingViewModel.TotalLocalGuestAmount
                        + tourPackage.BookingViewModel.TotalForeignAmount;

                    //set end date
                    DateTime endDate = new DateTime();
                    endDate = (DateTime)tourPackage.BookingViewModel.BookingStartDate;

                    if(tourPackage.BookingViewModel.TourDurationInHours / 24 > 1)
                        tourPackage.BookingViewModel.BookingEndDate = endDate.AddDays(((double)tourPackage.BookingViewModel.TourDurationInHours / 24) - 1);
                    else
                        tourPackage.BookingViewModel.BookingEndDate = endDate.AddDays(((double)tourPackage.BookingViewModel.TourDurationInHours / 24));

                    Booking booking = new Booking
                    {
                        GuestName = tourPackage.BookingViewModel.GuestName,
                        ContactNumber = tourPackage.BookingViewModel.ContactNumber,
                        EmailAddress = tourPackage.BookingViewModel.EmailAddress,
                        TourPackageId = tourPackage.BookingViewModel.TourPackageId,
                        TotalLocalGuest = tourPackage.BookingViewModel.TotalLocalGuest,
                        TotalChildGuest = tourPackage.BookingViewModel.TotalChildGuest,
                        TotalForeignGuest = tourPackage.BookingViewModel.TotalForeignGuest,
                        PickUpLocation = tourPackage.BookingViewModel.PickUpLocation,
                        BookingStartDate = tourPackage.BookingViewModel.BookingStartDate,
                        BookingEndDate = tourPackage.BookingViewModel.BookingEndDate,
                        TotalAmount = tourPackage.BookingViewModel.TotalAmount,
                        SpecialRequest = tourPackage.BookingViewModel.SpecialRequest,
                        BookingStatus = "ENTERED",
                        PaymentStatus = "PENDING",
                        IsConfirmed = false,
                        CreatedDate = System.DateTime.Now,
                        CreatedBy = "System"
                    };

                    if (tourPackageAddOnsIds != null)
                    {
                        var AddOns = new List<TourBookingAddOnsViewModel>();

                        foreach (int id in tourPackageAddOnsIds)
                        {
                            Console.WriteLine(id);

                            var addOn = entities.TourPackageAddOns.Find(id);

                            AddOns.Add(new TourBookingAddOnsViewModel()
                            {
                                TourPackageAddOnsId = id,
                                TourPackageAddOnsName = addOn.Name,
                                AddOnsPrice = (int)addOn.Price
                            });

                            entities.TourBookingAddOns.Add(new TourBookingAddOn
                            {
                                TourBookingId = booking.Id,
                                TourPackageAddOnsId = id,
                            });

                            entities.SaveChanges();

                        };

                        tourPackage.TourBookingAddOns = AddOns;
                        tourPackage.BookingViewModel.TourPackageAddOnsPrice = tourPackage.TourBookingAddOns.Sum(T => T.AddOnsPrice);

                    }

GoCebuTravelAndToursMVC/Views/Home/Facebook.cshtml
@{
    ViewBag.Title = "Facebook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-569e5ca9-73c5-4486-b80c-1abd6d6341f7"></div>

GoCebuTravelAndToursMVC/Views/Home/Index.cshtml
@model IEnumerable<GoCebuTravelAndToursMVC.TourPackage>

@{
    ViewBag.Title = "Home";
}


<div class="container-fluid">
    <div id="indicators" class="carousel slide" data-ride="carousel">
        @*<ol class="carousel-indicators">
                @{
                    <li data-target="#indicators" data-slide-to="0" class="active"></li>
                    if (Model != null)
                    {
                        for( int i = 1; i <= Model.Count(); i++ )
                        {
                            <li data-target="#indicators" data-slide-to="@i" class=""></li>
                        }
                    }

                }

            </ol>*@
        <div class="carousel-inner carousel-lay-inner " role="listbox">
            @{
                <div class="carousel-item carousel-lay-item active">
                    <div class="carousel-caption">
                    </div>
                    <img class="d-block w-100 h-100 carousel-img img-fluid" src="~/Content/img/tour/caro-first-active.jpg">

                </div>
                if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <div class="item carousel-item carousel-lay-item">
                            <div class="carousel-caption">
                                <h4 class="carousel-title">@item.TourPackageName</h4>
                                <hr class="carousel-hr" align="center" width="50%"/>
                                <a href='@Url.Action("TourPackage", "Tour", new { Id = item.Id, Package = item.TourPackageName})' class="btn btn-primary carousel-btn">Learn more</a>
                            </div>
                            <img class="d-block w-100 h-100 carousel-img img-fluid" src="~/Content/img/tour/@item.CaroImgFileName">
                        </div>
                    }
                }
            }

        </div>

        <a class="carousel-control-prev" href="#indicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#indicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>


    </div>
</div>


@Html.Action("ListTourPackages", "Home")

@Html.Action("Reviews", "Home")



@*<div id="map-home" class="container-fluid">
    <iframe style="width: 100%; height: 350px;" id="gmap_canvas" src="https://maps.google.com/maps?q=cebu&t=&z=9&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
</div>*@

GoCebuTravelAndToursMVC/Views/Home/ListTourPackages.cshtml
@model GoCebuTravelAndToursMVC.Models.ListTourPackageViewModel
@{
    GoCebuDBEntities entities = new GoCebuDBEntities();
}
<div id="list-tour-package" class="container">

    <h3>Day Tour Packages </h3>

    <hr />

    <div class="row" style="padding-top: 10px;">

        @foreach (var item in Model.TourPackages)
        {
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
                <div class="jumbotron">
                    @{
                        var isBestSellerClass = "";
                        if (item.BestSellerFlag == true)
                        {
                            isBestSellerClass = "box";
                        }
                    }

                    <div class="jumbotron-photo @isBestSellerClass">
                        @if (item.BestSellerFlag == true)
                        {
                            <div class="ribbon"><span>BEST SELLER</span></div>
                        }
                        <img src="~/Content/img/tour/@Html.DisplayFor(T => item.ImgFileName)">
                    </div>

                    <div class="jumbotron-contents">
                        <p class="package-title"> @Html.DisplayFor(modelItem => item.TourPackageName)</p>
                        <p class="package-description">@Html.Raw(HttpUtility.HtmlDecode(item.TourPackageDescription))</p>

                        <p class="text-info">
                            As low as
                            <strong>
                                <span>&#8369;</span><span class="as-low-as">
                                    @String.Format("{0:n}", @entities.TourPackagePrices.Where(T => T.TourPackageId == item.Id).Min(T => T.Amount))
                                </span>

                                / person
                            </strong>
                        </p>
                        <a href='@Url.Action("TourPackage", "Tour", new { Id = item.Id, Package = item.TourPackageName})' class="btn btn-primary btn-details">Learn more</a>
                    </div>
                </div>


            </div>


        }

    </div>
    <a href='@Url.Action("ListTourPackages", "Tour", new { groupBy = "all"  })'>See all tour packages</a>

</div>

GoCebuTravelAndToursMVC/Views/Home/Reviews.cshtml
@model IEnumerable<GoCebuTravelAndToursMVC.Review>


<div id="review" class="container">
    <div class="row">
        <div class="col-md-12">
            @if (Model.ToList().Count > 0)
            {

                <h3 style="text-align:center;">Reviews from our Guest</h3>
                <hr />
                <div id="review-carousel" class="carousel carousel-review slide" data-ride="carousel">
                    <ol class="carousel-indicators carousel-review-indicators">
                        <li data-target="#review-carousel" data-slide-to="0" class="active"></li>
                        @if (Model != null)
                        {
                            int i = 1;
                            foreach (var item in Model)
                            {
                                <li data-target="##eview-carousel" data-slide-to="@i" class=""></li>
                                i++;
                            }
                        }
                    </ol>
                    <div class="carousel-inner">
                        @{
                            var isActive = "active";
                        }

                        @foreach (var review in Model)
                        {
                            <div class="item carousel-review-item carousel-item @isActive">
                                <div class="img-box"><img src="~/Content/Img/reviews/@review.ImgFileName" alt=""></div>
                                <p class="testimonial">@review.Review1</p>
                                <p class="overview">
                                    <b>@review.Name</b>
                                    @if (review.ReviewLink == "facebook")
                                    {
                                        <a href="https://www.facebook.com/pg/GoCebuTravelandTours/reviews/" target="_blank">Facebook Review</a>
                                    }
                                    else
                                    {
                                        <a href="#" target="_blank">Google Review</a>
                                    }

                                </p>
                                <div>
                                    @{
                                        //switch than loop
                                        switch (review.Ratings)
                                        {
                                            //&#9733;
                                            case 1:
                                                <span class="fa fa-star "></span>
                                                break;
                                            case 2:
                                                <span class="fa fa-star "></span>
                                                <span class="fa fa-star "></span>
                                                break;
                                            case 3:
                                                <span class="fa fa-star "></span>
                                                <span class="fa fa-star "></span>
                                                <span class="fa fa-star "></span>
                                                break;
                                            case 4:
                                                <span class="fa fa-star "></span>
                                                <span class="fa fa-star "></span>
                                                <span class="fa fa-star "></span>
                                                <span class="fa fa-star "></span>
                                                <span class="fa fa-star "></span>
                                                break;
                                            case 5:
                                                <span class="fa fa-star "></span>
                                                <span class="fa fa-star "></span>
                                                <span class="fa fa-star "></span>
                                                <span class="fa fa-star "></span>
                                                <span class="fa fa-star "></span>
                                                break;
                                        }

                                    }
                                </div>
                            </div>
                            isActive = "";
                        }


                    </div>
                    <a class="carousel-control left carousel-control-prev" href="#review-carousel" data-slide="prev">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a class="carousel-control right carousel-control-next" href="#review-carousel" data-slide="next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>

            }
        </div>

    </div>


</div>